name: CMake Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - rel/*
      - dev/*
      - main
      - ppc-support
  pull_request:
    branches:
      - rel/*
      - dev/*
      - main

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  VCPKG_GIT_REF: 8a9a97315aefb3f8bc5d81bf66ca0025938b9c91

jobs:


  build-ubuntu-x86:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Update package listings
        run: sudo apt-get update

      - name: Install Build Tools
        run: sudo apt-get install -y bison flex valgrind

      - name: Install Dependencies
        run: sudo apt-get install -y check libbz2-dev libcurl4-openssl-dev libjson-c-dev libmilter-dev libncurses5-dev libpcre3-dev libssl-dev libxml2-dev zlib1g-dev zlib1g

      - name: Install pytest for easier to read test results
        run: python3 -m pip install pytest

      - uses: lukka/get-cmake@v3.21.2

      - name: Create Build Directory
        shell: bash
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        working-directory: ${{runner.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run:
          cmake ${{runner.workspace}}/clamav -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DENABLE_STATIC_LIB=ON
          -DENABLE_EXAMPLES=ON

      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --config ${{ env.BUILD_TYPE }}

      - name: Test
        shell: bash
        working-directory: ${{runner.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{ env.BUILD_TYPE }} -V

  build-ubuntu-ppc64le:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Update package listings
        run: sudo apt-get update

      - name: Install Build Tools
        run: sudo apt-get install -y bison flex valgrind
        
      - name: Install Advance toolchain
        run: |
          sudo wget https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/ubuntu/dists/focal/6976a827.gpg.key
          sudo apt-key add 6976a827.gpg.key
          sudo touch /etc/apt/sources.list.d/add_sources.list
          echo 'deb https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/ubuntu focal at15.0' | sudo tee -a /etc/apt/sources.list.d/add_sources.list
          sudo apt-get update -y
          sudo apt-get install advance-toolchain-at15.0-cross-ppc64le -y
          

      - name: Install Dependencies
        run: sudo apt-get install -y check libbz2-dev libcurl4-openssl-dev libjson-c-dev libmilter-dev libncurses5-dev libpcre3-dev libssl-dev libxml2-dev zlib1g-dev

      - name: Install pytest for easier to read test results
        run: python3 -m pip install pytest

      - uses: lukka/get-cmake@v3.21.2
      
      - name: Build LibCheck
        run: |
          sudo git clone https://github.com/libcheck/check.git && cd check
          sudo mkdir build && cd build
          sudo autoreconf --install ..
          sudo ../configure --prefix=/opt/at15.0/ppc64le/ 
          sudo cmake .. -DCMAKE_TOOLCHAIN_FILE=../../crosscompile.cmake
          sudo make
          sudo make install DESTDIR=/opt/at15.0/ppc64le/
          sudo ldconfig

      - name: Create Build Directory
        shell: bash
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/build 

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        working-directory: ${{runner.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run:
          cmake ${{runner.workspace}}/clamav -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DENABLE_STATIC_LIB=ON
          -DENABLE_EXAMPLES=ON
          -DCMAKE_TOOLCHAIN_FILE=crosscompile.cmake
          -DCMAKE_PREFIX_PATH=/opt/at15.0/
          -DCMAKE_SYSROOT=/opt/at15.0/ppc64le/

      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --config ${{ env.BUILD_TYPE }} -DCMAKE_TOOLCHAIN_FILE=crosscompile.cmake

      - name: Test
        shell: bash
        working-directory: ${{runner.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{ env.BUILD_TYPE }} -V
